# Generated by Django 5.1.1 on 2024-09-24 06:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备类别')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别列表',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门列表',
            },
        ),
        migrations.CreateModel(
            name='HostModelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备型号')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_models', to='property.assettypelist', verbose_name='设备类别')),
            ],
            options={
                'verbose_name': '设备型号',
                'verbose_name_plural': '设备型号列表',
            },
        ),
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('service_tag', models.CharField(max_length=100, verbose_name='设备序列号')),
                ('receive_date', models.DateField(default=datetime.date.today, verbose_name='采购日期')),
                ('duration', models.PositiveIntegerField(default='1', verbose_name='存在时长（天数）')),
                ('user_name', models.CharField(max_length=100, verbose_name='使用用户')),
                ('dept', models.CharField(max_length=100, verbose_name='用户部门')),
                ('host_status', models.CharField(default='闲置', max_length=50, verbose_name='设备状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('host_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.assettypelist', verbose_name='设备类别')),
                ('host_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.hostmodellist', verbose_name='设备型号')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备列表',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('license_key', models.CharField(max_length=100, unique=True, verbose_name='密钥')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '软件',
                'verbose_name_plural': '软件列表',
            },
        ),
    ]
