# Generated by Django 5.1.1 on 2024-09-24 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='存在时长（天数）'),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='host_status',
            field=models.CharField(choices=[('闲置', '闲置'), ('使用中', '使用中'), ('报废', '报废')], default='闲置', max_length=50, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='software',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='property.department', verbose_name='所属部门'),
        ),
    ]
