# Generated by Django 5.1.1 on 2024-09-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_assetinfo_duration_alter_assetinfo_host_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinfo',
            name='dept',
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.department', verbose_name='所属部门'),
            preserve_default=False,
        ),
    ]
