# Generated by Django 5.1.1 on 2024-09-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_assetinfo_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinfo',
            name='duration',
        ),
    ]
