# Generated by Django 5.1.1 on 2024-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_assetinfo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='host_model',
            field=models.CharField(max_length=100, verbose_name='设备型号'),
        ),
        migrations.DeleteModel(
            name='HostModelList',
        ),
    ]
