# Generated by Django 5.1.1 on 2024-09-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_assetinfo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='service_tag',
            field=models.CharField(max_length=100, unique=True, verbose_name='设备序列号'),
        ),
    ]
