# Generated by Django 5.1.1 on 2024-09-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_rename_name_assettypelist_type_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetinfo',
            old_name='user',
            new_name='host_user',
        ),
    ]
