# Generated by Django 5.1.1 on 2024-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_assetinfo_host_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='host_status',
            field=models.CharField(choices=[('闲置', '闲置'), ('使用中', '使用中'), ('等待报废', '等待报废')], default='闲置', max_length=50, verbose_name='设备状态'),
        ),
    ]
